//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentomino {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pentomino.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancing Links Demo.
        /// </summary>
        public static string idsApplicationName {
            get {
                return ResourceManager.GetString("idsApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string idsCancelButton {
            get {
                return ResourceManager.GetString("idsCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentominoes....
        /// </summary>
        public static string idsLaunchPentominoesButton {
            get {
                return ResourceManager.GetString("idsLaunchPentominoesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku....
        /// </summary>
        public static string idsLaunchSudokuButton {
            get {
                return ResourceManager.GetString("idsLaunchSudokuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentominoes.
        /// </summary>
        public static string idsPentominoesWindowTitle {
            get {
                return ResourceManager.GetString("idsPentominoesWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive passes:  {0:n0}.
        /// </summary>
        public static string idsRecursivePassesFormat {
            get {
                return ResourceManager.GetString("idsRecursivePassesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows removed:  {0:n0}.
        /// </summary>
        public static string idsRowsRemovedFormat {
            get {
                return ResourceManager.GetString("idsRowsRemovedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions found:  {0:n0}.
        /// </summary>
        public static string idsSolutionsFoundFormat {
            get {
                return ResourceManager.GetString("idsSolutionsFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve.
        /// </summary>
        public static string idsSolveButton {
            get {
                return ResourceManager.GetString("idsSolveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solving ....
        /// </summary>
        public static string idsSolvingWithEllipsis {
            get {
                return ResourceManager.GetString("idsSolvingWithEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku.
        /// </summary>
        public static string idsSudokuWindowTitle {
            get {
                return ResourceManager.GetString("idsSudokuWindowTitle", resourceCulture);
            }
        }
    }
}
