//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pentomino {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pentomino.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancing Links Demo.
        /// </summary>
        public static string idsApplicationName {
            get {
                return ResourceManager.GetString("idsApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string idsCancel {
            get {
                return ResourceManager.GetString("idsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string idsCancelButton {
            get {
                return ResourceManager.GetString("idsCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ˅.
        /// </summary>
        public static string idsDownArrow {
            get {
                return ResourceManager.GetString("idsDownArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration: .
        /// </summary>
        public static string idsDurationLabel {
            get {
                return ResourceManager.GetString("idsDurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Month and Day.
        /// </summary>
        public static string idsGetMonthAndDayDialogTitle {
            get {
                return ResourceManager.GetString("idsGetMonthAndDayDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Pentominoes....
        /// </summary>
        public static string idsLaunchCalendarPentominoesButton {
            get {
                return ResourceManager.GetString("idsLaunchCalendarPentominoesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentominoes....
        /// </summary>
        public static string idsLaunchPentominoesButton {
            get {
                return ResourceManager.GetString("idsLaunchPentominoesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku....
        /// </summary>
        public static string idsLaunchSudokuButton {
            get {
                return ResourceManager.GetString("idsLaunchSudokuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ˂.
        /// </summary>
        public static string idsLeftArrow {
            get {
                return ResourceManager.GetString("idsLeftArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string idsMonthName_April {
            get {
                return ResourceManager.GetString("idsMonthName_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string idsMonthName_August {
            get {
                return ResourceManager.GetString("idsMonthName_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string idsMonthName_December {
            get {
                return ResourceManager.GetString("idsMonthName_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string idsMonthName_February {
            get {
                return ResourceManager.GetString("idsMonthName_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string idsMonthName_January {
            get {
                return ResourceManager.GetString("idsMonthName_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string idsMonthName_July {
            get {
                return ResourceManager.GetString("idsMonthName_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string idsMonthName_June {
            get {
                return ResourceManager.GetString("idsMonthName_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string idsMonthName_March {
            get {
                return ResourceManager.GetString("idsMonthName_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string idsMonthName_May {
            get {
                return ResourceManager.GetString("idsMonthName_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string idsMonthName_November {
            get {
                return ResourceManager.GetString("idsMonthName_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string idsMonthName_October {
            get {
                return ResourceManager.GetString("idsMonthName_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string idsMonthName_September {
            get {
                return ResourceManager.GetString("idsMonthName_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string idsOk {
            get {
                return ResourceManager.GetString("idsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentominoes.
        /// </summary>
        public static string idsPentominoesWindowTitle {
            get {
                return ResourceManager.GetString("idsPentominoesWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize.
        /// </summary>
        public static string idsRandomize {
            get {
                return ResourceManager.GetString("idsRandomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive passes:  {0:n0}.
        /// </summary>
        public static string idsRecursivePassesFormat {
            get {
                return ResourceManager.GetString("idsRecursivePassesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ˃.
        /// </summary>
        public static string idsRightArrow {
            get {
                return ResourceManager.GetString("idsRightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows removed:  {0:n0}.
        /// </summary>
        public static string idsRowsRemovedFormat {
            get {
                return ResourceManager.GetString("idsRowsRemovedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions found:  {0:n0}.
        /// </summary>
        public static string idsSolutionsFoundFormat {
            get {
                return ResourceManager.GetString("idsSolutionsFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve.
        /// </summary>
        public static string idsSolveButton {
            get {
                return ResourceManager.GetString("idsSolveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku.
        /// </summary>
        public static string idsSudokuWindowTitle {
            get {
                return ResourceManager.GetString("idsSudokuWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ˄.
        /// </summary>
        public static string idsUpArrow {
            get {
                return ResourceManager.GetString("idsUpArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ....
        /// </summary>
        public static string idsWorkingWithEllipsis {
            get {
                return ResourceManager.GetString("idsWorkingWithEllipsis", resourceCulture);
            }
        }
    }
}
